# Generated by Django 2.2.1 on 2020-02-22 14:01

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DiabeticRetinopathy', '0002_auto_20200207_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 2, 22, 14, 1, 53, 486126))),
                ('photo', models.ImageField(null=True, upload_to='fundus_images')),
            ],
        ),
    ]
